# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-24 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_auto_20160424_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='current',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='study.Student'),
            preserve_default=False,
        ),
    ]
